# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths D:/study/embled/ip_repo/led_ip_1.0 [current_fileset]
read_verilog -library xil_defaultlib {
  D:/study/embled/ip_repo/led_ip_1.0/hdl/led_ip_v1_0_S_AXI.v
  D:/study/embled/ip_repo/led_ip_1.0/hdl/led_ip_v1_0.v
  D:/study/embled/ip_repo/edit_led_ip_v1_0.srcs/sources_1/imports/hdl/lab3_user_logic.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/study/embled/ip_repo/edit_led_ip_v1_0.cache/wt [current_project]
set_property parent.project_dir D:/study/embled/ip_repo [current_project]
catch { write_hwdef -file led_ip_v1_0.hwdef }
synth_design -top led_ip_v1_0 -part xc7z010clg400-1
write_checkpoint led_ip_v1_0.dcp
report_utilization -file led_ip_v1_0_utilization_synth.rpt -pb led_ip_v1_0_utilization_synth.pb
